# Generated by Django 4.2.4 on 2023-12-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_visitante_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='morador_responsavel',
            field=models.CharField(blank=True, max_length=194, verbose_name='Responsável pela autorização'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='numero_casa',
            field=models.PositiveSmallIntegerField(verbose_name='Empresa visitada'),
        ),
    ]
