# Generated by Django 4.2.4 on 2023-12-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_alter_visitante_morador_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=124, null=True, verbose_name='Empresa visitada'),
        ),
    ]
